# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: FlatmapVuer CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run cypress:record
      env:
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        HUMAN_FEMALE_UUID: ${{ secrets.HUMAN_FEMALE_UUID }}
        HUMAN_MALE_UUID: ${{ secrets.HUMAN_MALE_UUID }}
        RAT_UUID: ${{ secrets.RAT_UUID }}
        MOUSE_UUID: ${{ secrets.MOUSE_UUID }}
        PIG_UUID: ${{ secrets.PIG_UUID }}
        CAT_UUID: ${{ secrets.CAT_UUID }}
